### ISSUE TITLE
Extra line in Create mod plaques | Visual Bug | Forge/NeoForge | 1.20.1

### ISSUE THREAD

**Issue by DavidTs93** [AHilyard/Iceberg#54] opened 2023-10-13 14:04 UTC
When running Iceberg and the Create mod together (even when running ONLY these 2) a visual bug appears when wearing the Create mod's Goggles - the text in the plaque goes down one line which makes it come out of the background.
This happens for all items from Create that get this plaque.

## Example of the bug
![Example of the bug](https://raw.githubusercontent.com/DavidTs93/DavidTs93.github.io/main/Images/IcebergBug/Bug.png)

## Example of non-bugged
![Example of non-bugged](https://raw.githubusercontent.com/DavidTs93/DavidTs93.github.io/main/Images/IcebergBug/Normal.png)

**Comment by AHilyard** [comment] 2023-12-14 01:54
Duplicate of https://github.com/AHilyard/Iceberg/issues/17. Hopefully will be fixed soon by Create (See linked PR).

**Closed by AHilyard** 2023-12-14 01:54 UTC
